language: node_js
services:
  - rabbitmq
node_js:
  - '4'
env:
  - MQ_USERNAME=guest MQ_PASSWORD=guest MQ_CONNECTION_URI="amqp://localhost:5671/"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
